blog/urls.py
from django.urls import path
from . import views
from django.urls import include

app_name='blog'

urlpatterns = [
	path('', views.index, name="index"),
	path('<int:article_id>/<slug:slug>/detail/', views.detail, name='detail'),

	# path('tinymce/', include('tinymce.urls')),
	# path('subscribe/', views.subscribe, name='subscribe'),
]

dentweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns


urlpatterns = i18n_patterns(
    path('bckend-admin/', admin.site.urls),
		path('', include('main.urls')),
		path('<str:name>/blog/', include('blog.urls')),
		path('cstm-admin-panel/', include('dentadmin.urls')),

		path('tinymce/', include('tinymce.urls')),

		# path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
		# path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),

		path('<str:name>/', views.trgt_index, name="trgt_index"),

    path('accounts/logout/', views.custom_logout, name='logout'),
    path('accounts/signup/', views.sigunp, name="signup"),
    path('accounts/password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path("accounts/", include("django.contrib.auth.urls")),
		
		path('<str:name>/contact-us/', views.contact_us_page, name="contact_us_page"),

		# Without name
		path('contact/', views.contact_us_page, name="contact_page"),
]

templates/footer.html
{% load static %}
{% load i18n %}
{% get_current_language as CURRENT_LANGUAGE %}

{% if CURRENT_LANGUAGE == 'ar' %}

<footer class="bg-main-gradient">
	<div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
		<div class="flex justify-center gap-7 flex-col md:flex-row-reverse md:gap-0 md:justify-between">
			<div class="mb-6 md:mb-0">
				{% if name %}
						<a href="{% url 'main:trgt_index' name=name %}" class="flex items-center">
								<img src="{% static 'imgs/dentals/'|add:name|add:'.png' %}" class="max-h-32 max-w-sm shadow-2xl" alt="Logo" />
						</a>
				{% else %}
						<a href="{% url 'main:index' %}" class="flex items-center">
								<img src="{% static 'imgs/fav.jpeg' %}" class="max-h-32 max-w-sm shadow-2xl" alt="Logo" />
						</a>
				{% endif %}
			</div>
			<div class="text-right">
				<h2 class="mb-6 md:text-2xl  font-bold uppercase text-white">{% trans "Contact Information" %}</h2>
				<ul class="text-gray-100 text-xl font-medium">
					<li class="mb-4">
						<a href="">+1800 456 789</a>
					</li>
					<li>
						<a href="">+1800 456 780</a>
					</li>
				</ul>
			</div>
			<div class="text-right">
				<h2 class="mb-6 md:text-2xl  font-bold uppercase text-white">{% trans "Open Hours" %}</h2>
				<ul class="text-gray-100 text-xl font-medium">
					<li class="mb-4">
						<a href="#">{% trans "Mon-Fri 09:00 - 19:00" %}</a>
					</li>
					<li>
						<a href="#">{% trans "Sat-Sun 10:00 - 14:00" %}</a>
					</li>
				</ul>
			</div>
			<div class="text-right">
				<h2 class="mb-6 md:text-2xl  font-bold uppercase text-white">{% trans "Reach Us" %}</h2>
				<ul class="text-gray-100 text-xl font-medium">
					<li class="mb-4">
						<a href=""">{% trans "456 Smile Avenue, Dental City, CA 90210" %}</a>
					</li>
				</ul>
			</div>
		</div>
		<hr class="my-6 border-gray-100 sm:mx-auto lg:my-8" />
			<div class="sm:flex sm:items-center sm:justify-end">
				<span class="text-sm text-gray-100 sm:text-center ">© 2024 <a href="https://socialcodepk.com/" class="underline" target="_blank"
					>SocialCodePk</a>. {% trans "All Rights Reserved." %}
				</span>
			</div>
	</div>
</footer>

{% elif CURRENT_LANGUAGE == 'en' %}

<footer class="bg-main-gradient">
	<div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
		<div class="flex justify-center gap-7 flex-col md:flex-row md:gap-0 md:justify-between">
			<div class="mb-6 md:mb-0">
				{% if name %}
						<a href="{% url 'main:trgt_index' name=name %}" class="flex items-center">
								<img src="{% static 'imgs/dentals/'|add:name|add:'.png' %}" class="max-h-32 max-w-sm shadow-2xl" alt="Logo" />
						</a>
				{% else %}
						<a href="{% url 'main:index' %}" class="flex items-center">
								<img src="{% static 'imgs/fav.jpeg' %}" class="max-h-32 max-w-sm shadow-2xl" alt="Logo" />
						</a>
				{% endif %}

			</div>
			<div>
				<h2 class="mb-6 md:text-2xl  font-bold uppercase text-white">{% trans "Contact Information" %}</h2>
				<ul class="text-gray-100 text-xl font-medium">
					<li class="mb-4">
						<a href="">+1800 456 789</a>
					</li>
					<li>
						<a href="">+1800 456 780</a>
					</li>
				</ul>
			</div>
			<div>
				<h2 class="mb-6 md:text-2xl  font-bold uppercase text-white">{% trans "Open Hours" %}</h2>
				<ul class="text-gray-100 text-xl font-medium">
					<li class="mb-4">
						<a href="#">{% trans "Mon-Fri 09:00 - 19:00" %}</a>
					</li>
					<li>
						<a href="#">{% trans "Sat-Sun 10:00 - 14:00" %}</a>
					</li>
				</ul>
			</div>
			<div>
				<h2 class="mb-6 md:text-2xl  font-bold uppercase text-white">{% trans "Reach Us" %}</h2>
				<ul class="text-gray-100 text-xl font-medium">
					<li class="mb-4">
						<a href=""">{% trans "456 Smile Avenue, Dental City, CA 90210" %}</a>
					</li>
				</ul>
			</div>
		</div>
		<hr class="my-6 border-gray-100 sm:mx-auto lg:my-8" />
			<div class="sm:flex sm:items-center sm:justify-between">
				<span class="text-sm text-gray-100 sm:text-center ">© 2024 <a href="https://socialcodepk.com/" class="underline" target="_blank"
					>SocialCodePk</a>. {% trans "All Rights Reserved." %}
				</span>
			</div>
	</div>
</footer>

{% endif %}

templates/nav.html
{% load i18n %}
{% load static %}

<nav class="fixed w-full z-20 top-0 start-0 bg-main-gradient rounded-br-full">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
		{% if name %}
    <a href="{% url 'main:trgt_index' name=name %}" class="flex items-center space-x-3 rtl:space-x-reverse">
      <img src="{% static 'imgs/dentals/'|add:name|add:'.png' %}" class="h-8" />
      <span class="self-center text-2xl font-semibold whitespace-nowrap text-white">{{ name }}</span>
    </a>
		{% else %}
		<a href="{% url 'main:index' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
      <img src="{% static 'imgs/fav.jpeg' %}" class="h-8" alt="Flowbite Logo" />
      <span class="self-center text-2xl font-semibold whitespace-nowrap text-white">{% trans "This Could Be Yours" %}</span>
    </a>
		{% endif %}
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex mr-5 items-center p-2 w-10 h-10 justify-center text-sm text-gray-50 rounded-lg md:hidden focus:outline-none focus:ring-2 focus:ring-gray-200" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 rounded-lg md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0">

				{% comment %}

        <li class="py-2 rounded-2xl">
          <a href="{% url 'blog:index' name=name %}" class="text-xl font-bold block py-2 px-3 rounded nav-txt md:hover:underline md:hover:bg-transparent hover:bg-gray-100 md:border-0 md:p-0 md:hover:text-white text-white">{% trans "Blog" %}</a>
        </li>

				{% endcomment %}
        
				{% get_current_language as CURRENT_LANGUAGE %}

				{% if name %}

					{% if CURRENT_LANGUAGE == 'ar' %}

					<li class="py-2 rounded-2xl hidden lg:block">
						<a href="{% url 'main:trgt_index' name=name %}#services" class="text-xl font-bold block py-2 px-3 rounded nav-txt md:hover:underline md:hover:bg-transparent hover:bg-gray-100 md:border-0 md:p-0 md:hover:text-white text-white">{% trans "Services" %}</a>
					</li>
					<li class="py-2 rounded-2xl block lg:hidden">
						<a href="{% url 'main:trgt_index' name=name %}#services-blw-lg" class="text-xl font-bold block py-2 px-3 rounded nav-txt md:hover:underline md:hover:bg-transparent hover:bg-gray-100 md:border-0 md:p-0 md:hover:text-white text-white">{% trans "Services" %}</a>
					</li>

					{% elif CURRENT_LANGUAGE == "en" %}

					<li class="py-2 rounded-2xl">
						<a href="{% url 'main:trgt_index' name=name %}#services" class="text-xl font-bold block py-2 px-3 rounded nav-txt md:hover:underline md:hover:bg-transparent hover:bg-gray-100 md:border-0 md:p-0 md:hover:text-white text-white">{% trans "Services" %}</a>
					</li>

					{% endif %}

				{% else %}

					{% if CURRENT_LANGUAGE == 'ar' %}

					<li class="py-2 rounded-2xl hidden lg:block">
						<a href="{% url 'main:index' %}#services" class="text-xl font-bold block py-2 px-3 rounded nav-txt md:hover:underline md:hover:bg-transparent hover:bg-gray-100 md:border-0 md:p-0 md:hover:text-white text-white">{% trans "Services" %}</a>
					</li>
					<li class="py-2 rounded-2xl block lg:hidden">
						<a href="{% url 'main:index' %}#services-blw-lg" class="text-xl font-bold block py-2 px-3 rounded nav-txt md:hover:underline md:hover:bg-transparent hover:bg-gray-100 md:border-0 md:p-0 md:hover:text-white text-white">{% trans "Services" %}</a>
					</li>

					{% elif CURRENT_LANGUAGE == "en" %}

					<li class="py-2 rounded-2xl">
						<a href="{% url 'main:index' %}#services" class="text-xl font-bold block py-2 px-3 rounded nav-txt md:hover:underline md:hover:bg-transparent hover:bg-gray-100 md:border-0 md:p-0 md:hover:text-white text-white">{% trans "Services" %}</a>
					</li>

					{% endif %}

				{% endif %}

				{% if request.user.is_authenticated %}
				<li class="py-2 rounded-2xl hidden lg:block">
					<a href="{% url 'main:logout' %}?next={{ request.path }}" class="text-xl font-bold block py-2 px-3 rounded nav-txt md:hover:underline md:hover:bg-transparent hover:bg-gray-100 md:border-0 md:p-0 md:hover:text-white text-white">{% trans "Logout" %}</a>
				</li>
				{% endif %}
        
				{% comment %}

        <li class="py-2 rounded-2xl">
          <div class="relative">
            <button id="dropdownLanguageLink" data-dropdown-toggle="dropdownLanguage" class="text-xl font-bold inline-flex items-center py-2 px-3 rounded nav-txt md:hover:underline md:hover:bg-transparent hover:bg-gray-100 md:border-0 md:p-0 md:hover:text-white text-white">
              {% trans "Language" %}
              <svg class="w-2.5 h-2.5 ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
              </svg>
            </button>
            <div id="dropdownLanguage" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44">
              <ul class="py-2 text-sm text-gray-700">
                <li class="py-1">
                  <a href="#" data-language="ar" class="block px-4 py-2 nav-txt">العربية</a>
                </li>
                <li class="py-1">
                  <a href="#" data-language="en" class="block px-4 py-2 nav-txt">English</a>
                </li>
              </ul>
            </div>
          </div>
        </li>

				{% endcomment %}

				<li class="py-2 rounded-2xl">
          <div class="relative">
            <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar" class="text-xl font-bold inline-flex items-center py-2 px-3 rounded nav-txt md:hover:underline md:hover:bg-transparent hover:bg-gray-100 md:border-0 md:p-0 md:hover:text-white text-white">
              {% trans "Themes" %}
              <svg class="w-2.5 h-2.5 ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
              </svg>
            </button>
            <div id="dropdownNavbar" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44">
              <ul class="py-2 text-sm text-gray-700">
                <li class="py-1">
                  <a onclick="switchTheme('')" href="#" class="block px-4 py-2 nav-txt">{% trans "Teal & Green" %}</a>
                </li>
                <li class="py-1">
                  <a onclick="switchTheme('indigo-purple')" href="#" class="block px-4 py-2 nav-txt">{% trans "Indigo & Purple" %}</a>
                </li>
                <li class="py-1">
                  <a onclick="switchTheme('red-amber')" href="#" class="block px-4 py-2 nav-txt">{% trans "Red & Amber" %}</a>
                </li>
              </ul>
            </div>
          </div>
        </li>

				{% if name %}

        <li class="py-2 rounded-2xl">
          <a href="{% url 'main:contact_us_page' name=name %}" class="text-xl font-bold block py-2 px-3 rounded nav-txt md:hover:underline md:hover:bg-transparent hover:bg-gray-100 md:border-0 md:p-0 md:hover:text-white text-white">{% trans "Contact Us" %}</a>
        </li>

				{% else %}

				<li class="py-2 rounded-2xl">
          <a href="{% url 'main:contact_page' %}" class="text-xl font-bold block py-2 px-3 rounded nav-txt md:hover:underline md:hover:bg-transparent hover:bg-gray-100 md:border-0 md:p-0 md:hover:text-white text-white">{% trans "Contact Us" %}</a>
        </li>

				{% endif %}
    
				{% get_current_language as CURRENT_LANGUAGE %}

				{% if name %}

					{% if CURRENT_LANGUAGE == 'ar' %}

					<li class="py-2 rounded-2xl hidden lg:block">
						<a href="{% url 'main:trgt_index' name=name %}#book-an-appointment-ar" class="border border-gray-100 text-white rounded-xl hover:bg-gray-50 nav-txt hover:border-0 focus:ring-4 focus:outline-none focus:ring-white font-bold text-xl px-5 py-2.5 text-center">
							{% trans "Book an Appointment" %}
						</a>
					</li>
					<li class="py-2 rounded-2xl block lg:hidden">
						<a href="{% url 'main:trgt_index' name=name %}#book-an-appointment-ar-blw-lg" class="border border-gray-100 text-white rounded-xl hover:bg-gray-50 nav-txt hover:border-0 focus:ring-4 focus:outline-none focus:ring-white font-bold text-xl px-5 py-2.5 text-center">
							{% trans "Book an Appointment" %}
						</a>
					</li>

					{% elif CURRENT_LANGUAGE == 'en' %}
					
					<li class="py-2 rounded-2xl">
						<a href="{% url 'main:trgt_index' name=name %}#book-an-appointment" class="border border-gray-100 text-white rounded-xl hover:bg-gray-50 nav-txt hover:border-0 focus:ring-4 focus:outline-none focus:ring-white font-bold text-xl px-5 py-2.5 text-center">
							{% trans "Book an Appointment" %}
						</a>
					</li>

					{% endif %}

				{% else %}

					{% if CURRENT_LANGUAGE == 'ar' %}

					<li class="py-2 rounded-2xl hidden lg:block">
						<a href="{% url 'main:index' %}#book-an-appointment-ar" class="border border-gray-100 text-white rounded-xl hover:bg-gray-50 nav-txt hover:border-0 focus:ring-4 focus:outline-none focus:ring-white font-bold text-xl px-5 py-2.5 text-center">
							{% trans "Book an Appointment" %}
						</a>
					</li>
					<li class="py-2 rounded-2xl block lg:hidden">
						<a href="{% url 'main:index' %}#book-an-appointment-ar-blw-lg" class="border border-gray-100 text-white rounded-xl hover:bg-gray-50 nav-txt hover:border-0 focus:ring-4 focus:outline-none focus:ring-white font-bold text-xl px-5 py-2.5 text-center">
							{% trans "Book an Appointment" %}
						</a>
					</li>

					{% elif CURRENT_LANGUAGE == 'en' %}
					
					<li class="py-2 rounded-2xl">
						<a href="{% url 'main:index' %}#book-an-appointment" class="border border-gray-100 text-white rounded-xl hover:bg-gray-50 nav-txt hover:border-0 focus:ring-4 focus:outline-none focus:ring-white font-bold text-xl px-5 py-2.5 text-center">
							{% trans "Book an Appointment" %}
						</a>
					</li>

					{% endif %}

				{% endif %}

      </ul>
    </div>
  </div>
</nav>

<script>
  // Set default language in localStorage if not already set
  if (!localStorage.getItem('selectedLanguage')) {
    localStorage.setItem('selectedLanguage', '{{ CURRENT_LANGUAGE }}');
  }

  // Update language in localStorage when user selects a language
  document.querySelectorAll('[data-language]').forEach(link => {
    link.addEventListener('click', function(event) {
      event.preventDefault();
      const selectedLanguage = this.getAttribute('data-language');
      localStorage.setItem('selectedLanguage', selectedLanguage);

      // Get the current path and replace the language prefix
      const currentPath = window.location.pathname;
      const pathWithoutLanguage = currentPath.replace(/^\/\w{2}/, '');
      const newPath = `/${selectedLanguage}${pathWithoutLanguage}`;
      
      // Redirect to the new language URL
      window.location.href = newPath;
    });
  });

  // Apply stored language on page load
  window.addEventListener('load', () => {
    const selectedLanguage = localStorage.getItem('selectedLanguage');
    if (selectedLanguage) {
      // Update language dropdown based on the selected language
      document.querySelectorAll('[data-language]').forEach(link => {
        const href = link.getAttribute('href');
        link.setAttribute('href', `/${selectedLanguage}${href}`);
      });
    }
  });
</script>